<?php

/**
 * @var \Magento\Customer\Api\Data\AttributeMetadataInterface $attribute
 * @var \Tangkoko\CustomerAttributesManagement\Block\Attributes\AbstractElement $block
 * @var \Magento\Framework\Escaper $escaper
 */

use Tangkoko\CustomerAttributesManagement\Block\Attributes\AbstractElement;

$attribute = $block->getAttribute();
if ($attribute) :
?>
    <input type="hidden" name="<?= $attribute->getAttributeCode() ?>" id="<?= $attribute->getAttributeCode() ?>" value="<?= $block->escapeHtmlAttr($block->getValue()) ?>" title="<?= $block->escapeHtmlAttr(__($attribute->getStoreLabel())) ?>" class="input-text <?= $attribute->getFrontendClass() ?>" data-validate="<?= $escaper->escapeHtmlAttr($block->getViewModel()->getValidationRules($attribute)) ?>" />
<?php
endif;
?>