<?php
/**
 * @var \Magento\Customer\Api\Data\AttributeMetadataInterface $attribute
 */
$attribute = $block->getAttribute();
if($attribute):
    $block->getAttributeValue();
    ?>
    <div class="field <?= $attribute->getAttributeCode() ?> <?= $attribute->isRequired()?"required":"" ?>">
        <label for="<?= $attribute->getAttributeCode() ?>" class="label">
    <span>
        <?= $block->escapeHtml(__($attribute->getStoreLabel())) ?>
    </span>
        </label>
        <div class="control">
            <select multiple
                    name="<?= $attribute->getAttributeCode() ?>[]"
                    id="<?= $attribute->getAttributeCode() ?>"
                    title="<?= $block->escapeHtmlAttr(__($attribute->getStoreLabel())) ?>"
                    class="<?= $attribute->getFrontendClass() ?>">
                <?php foreach ($attribute->getOptions() as $option):?>
                    <option value="<?= $option->getValue() ?>" <?= in_array($option->getValue(), $block->getAttributeValue())?"selected":""?>><?= $option->getLabel() ?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>
<?php
endif;
?>