<?php

/**
 * @var \Tangkoko\CustomerAttributesManagement\Block\Attributes\AbstractElement $block
 * @var \Magento\Customer\Api\Data\AttributeMetadataInterface $attribute
 */


$attribute = $block->getAttribute();
if ($attribute) :
?>
    <div class="field <?= $attribute->getAttributeCode() ?> <?= $attribute->getIsRequired() ? "required" : "" ?>">
        <label for="<?= $attribute->getAttributeCode() ?>" class="label">
            <span>
                <?= $block->escapeHtml(__($attribute->getStoreLabel())) ?>
            </span>
        </label>
        <?php foreach ($attribute->getOptions() as $option) : ?>
            <div class="control">
                <input type="radio" data-validate="<?= $escaper->escapeHtmlAttr($block->getValidationRules($attribute)) ?>" value="<?= $option->getValue() ?>" id="<?= $attribute->getAttributeCode() ?>-<?= $option->getValue() ?>" class="<?= $attribute->getFrontendClass() ?>" <?= ($block->escapeHtmlAttr($block->getValue()) == $option->getValue()) ? "checked" : "" ?> />
                <label for="<?= $attribute->getAttributeCode() ?>-<?= $option->getValue() ?>"></label>
            </div>
        <?php endforeach; ?>
    </div>
<?php
endif;
?>