<?php

/**
 * @var \Magento\Eav\Api\Data\AttributeInterface $attribute
 * @var \Tangkoko\CustomerAttributesManagement\Block\Attributes\AbstractElement $block
 * @var \Magento\Framework\Escaper $escaper
 */

use Tangkoko\CustomerAttributesManagement\Block\Attributes\AbstractElement;

$attribute = $block->getAttribute();
if ($attribute) :
?>
    <div class="field <?= $attribute->getAttributeCode() ?> <?= $attribute->getIsRequired() ? "required" : "" ?>">
        <label for="<?= $attribute->getAttributeCode() ?>" class="label">
            <span>
                <?= $block->escapeHtml(__($attribute->getStoreLabel())) ?>
            </span>
        </label>
        <div class="control">
            <input type="text" placeholder="<?= $attribute->getExtensionAttributes()->getCamAttribute() ? $attribute->getExtensionAttributes()->getCamAttribute()->getPlaceholder() : "" ?>" name="<?= $attribute->getAttributeCode() ?>" id="<?= $attribute->getAttributeCode() ?>" value="<?= $block->escapeHtmlAttr($block->getValue()) ?>" title="<?= $block->escapeHtmlAttr(__($attribute->getStoreLabel())) ?>" class="input-text <?= $attribute->getFrontendClass() ?>" data-validate="<?= $escaper->escapeHtmlAttr($block->getViewModel()->getValidationRules($attribute)) ?>" />
        </div>
    </div>
<?php
endif;
?>