<?php

/**
 * @var \Tangkoko\CustomerAttributesManagement\Block\Address\Form\Attributes\Street $block
 * 
 */
$_street = $block->getAttribute()->getFrontendLabel();
/**
 * @var \Tangkoko\CustomerAttributesManagement\ViewModel\Address $viewModel
 */
$viewModel = $block->getViewModel();
$_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street');
$_streetValidationClassNotRequired = $_streetValidationClass !== null ? trim(str_replace('required-entry', '', $_streetValidationClass)) : '';
?>
<div class="field street required">
    <label for="street_1" class="label"><span><?= /* @noEscape */ $_street  ?></span></label>
    <div class="control">
        <div class="field primary">
            <label for="street_1" class="label">
                <span>
                    <?= $escaper->escapeHtml(__('Street Address: Line %1', 1)) ?>
                </span>
            </label>
        </div>
        <input type="text" name="street[0]" placeholder="<?= $viewModel->addressGetStreetLinesPlaceholder(0) ?>" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= /* @noEscape */ $_street ?>" id="street_1" class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>" />
        <div class="nested">
            <?php for ($_i = 1, $_n = $viewModel->addressGetStreetLines(); $_i < $_n; $_i++) : ?>
                <div class="field additional">
                    <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                        <span><?= $escaper->escapeHtml(__('Street Address: Line %1', $_i + 1)) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="street[<?= /* @noEscape */ $_i ?>]" placeholder="<?= $viewModel->addressGetStreetLinesPlaceholder($_i) ?>" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>" id="street_<?= /* @noEscape */ $_i + 1 ?>" class="input-text
                                <?= $escaper->escapeHtmlAttr($_streetValidationClassNotRequired) ?>">
                    </div>
                </div>
            <?php endfor; ?>
        </div>
    </div>
</div>