<?php

/**
 * @var \Tangkoko\CustomerAttributesManagement\Block\Address\Form\Edit\Attributes $block
 */

?>
<?php foreach ($block->getAttributes() as $attribute) : ?>
    <?= $block->getChildHtml($block->getNameInLayout() . '.' .  $attribute->getAttributeCode()) ?>
<?php endforeach; ?>


<script type="text/x-magento-init">
    {
        "<?= $block->getFormSelector() ?>": {
            "camDependencies": {
                "config":<?= $block->getJsonConfig() ?> 
            }
        }
    }
</script>